export interface DataStoreType {
  id: string;
  createdAt: string;
  updatedAt: string;
  company1: string;
  no1: string;
  company: string;
  tel0: string;
  tel1: string;
  tel2: string;
  tel3: string;
  tel: string;
  id3: string;
  no: string;
  mail1: string;
  zip1: string;
  zip: string;
  address1: string;
  URL: string;
  XML: string;
  longitude: string;
  latitude: string;
  ido: string;
  mail: string;
  ID: string;
  address: string;
  keido: string;
  lat: string;
  lon: string;
  geolocation: string;
  active: string;
  hp1: string;
  map: string;
  hp0: string;
  hp: string;
  id1: string;
  id2: string;
  hpmail1: string;
  hpmail2: string;
  hpmail: string;
  program1: string;
  program: string;
  download: string;
  com2: string;
  com: string;
}

export type FileStoreRecord = Record<string, unknown> & {
  id: string;
  createdAt: string;
  updatedAt: string;
};
